[package]
name = "veloren-client"
version = "0.2.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
common = { package = "veloren-common", path = "../common" }

log = "0.4"
specs = "0.14"
vek = "0.9"
uvth = "3.1.0"
num_cpus = "1"
