[package]
name = "veloren-client"
version = "0.5.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
common = { package = "veloren-common", path = "../common", features = ["no-assets"] }

byteorder = "1.3.2"
uvth = "3.1.1"
image = "0.22.3"
num_cpus = "1.10.1"
log = "0.4.8"
specs = "0.15.1"
vek = { version = "0.10.0", features = ["serde"] }
hashbrown = { version = "0.6.2", features = ["rayon", "serde", "nightly"] }
authc = { git = "https://gitlab.com/veloren/auth.git", rev = "65571ade0d954a0e0bd995fdb314854ff146ab97" }
