[package]
name = "veloren-client"
version = "0.2.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
common = { package = "veloren-common", path = "../common" }

uvth = "3.1.0"
num_cpus = "1.10.1"
log = "0.4.7"
specs = "0.14.2"
vek = "0.9.8"
