[package]
name = "veloren-client"
version = "0.6.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
common = { package = "veloren-common", path = "../common", features = ["no-assets"] }

byteorder = "1.3.2"
uvth = "3.1.1"
image = { version = "0.22.3", default-features = false, features = ["png"] }
num_cpus = "1.10.1"
log = "0.4.8"
specs = "0.15.1"
vek = { version = "0.11.0", features = ["serde"] }
hashbrown = { version = "0.6", features = ["rayon", "serde", "nightly"] }
authc = { git = "https://gitlab.com/veloren/auth.git", rev = "223a4097f7ebc8d451936dccb5e6517194bbf086" }
