stages:
    - optional-builds
    - check-compile
    - build-post
    - publish

variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 3
    GIT_CLEAN_FLAGS: -f

default:
  image: registry.gitlab.com/veloren/veloren-docker-ci:latest
  # https://docs.gitlab.com/ee/ci/pipelines/settings.html#auto-cancel-pending-pipelines
  interruptible: true


before_script:
    - source $HOME/.cargo/env
    - df -h /
    - free -h
    - cargo --version
    - export DISABLE_GIT_LFS_CHECK=true
    - export VELOREN_ASSETS="$(pwd)/assets"
    - echo "VELOREN_ASSETS=$VELOREN_ASSETS"
    - rm -r target || echo "target doesnt exist, which is fine"
    - ln -s /dockercache/veloren/target target

include:
    - local: .gitlab/CI/optional-builds.gitlab-ci.yml
    - local: .gitlab/CI/check-compile.gitlab-ci.yml
    - local: .gitlab/CI/build-post.gitlab-ci.yml
    - local: .gitlab/CI/publish.gitlab-ci.yml
