[package]
name = "veloren-world"
version = "0.2.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
common = { package = "veloren-common", path = "../common" }
vek = "0.9"
noise = "0.5"
hashbrown = "0.3.0"

[dev-dependencies]
minifb = { git = "https://github.com/emoon/rust_minifb.git" }
