[package]
name = "veloren-world"
version = "0.2.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
common = { package = "veloren-common", path = "../common" }
vek = "0.9"
noise = "0.5"
fxhash = "0.2"
lazy_static = "1.3"
rand = "0.5"

[dev-dependencies]
minifb = { git = "https://github.com/emoon/rust_minifb.git" }
