[package]
name = "veloren-world"
version = "0.6.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.0"
common = { package = "veloren-common", path = "../common" }
bitvec = "0.17.4"
fxhash = "0.2.1"
image = { version = "0.22.3", default-features = false, features = ["png"] }
itertools = "0.8.2"
vek = "0.11.0"
noise = { version = "0.6.0", default-features = false }
num = "0.2.0"
ordered-float = "1.0"
hashbrown = { version = "0.6", features = ["rayon", "serde", "nightly"] }
lazy_static = "1.4.0"
log = "0.4.8"
rand = "0.7"
rand_chacha = "0.2.1"
arr_macro = "0.1.2"
packed_simd = "0.3.3"
rayon = "^1.3.0"
roots = "0.0.5"
serde = "1.0"
serde_derive = "1.0"
ron = { version = "0.6", default-features = false }

[dev-dependencies]
pretty_env_logger = "0.3.0"
minifb = "0.14.0"
