[package]
name = "veloren_network"
version = "0.1.0"
authors = ["Marcel Märtens <marcel.cochem@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

enumset = { version = "0.4", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
tlid = { path = "../../tlid", features = ["serde"]}
#threadpool
uvth = "3.1"
#serialisation
bincode = "1.2"
serde = "1.0"
byteorder = "1.3"
#sending
mio = "0.6"
mio-extras = "2.0"
#tracing and metrics
tracing = "0.1"
prometheus = "0.7"
#async
futures = "0.3"
#mpsc channel registry
lazy_static = "1.4"
rand = "0.7"

[dev-dependencies]
tracing-subscriber = "0.2.3"