[package]
name = "veloren-server"
version = "0.2.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
common = { package = "veloren-common", path = "../common" }
world = { package = "veloren-world", path = "../world" }

log = "0.4"
specs = "0.14"
vek = "0.9"
uvth = "3.1.0"
lazy_static = "1.3.0"
scan_fmt = "0.1.3"
ron = "0.5.1"
serde = "1.0"
serde_derive = "1.0"