[controls]
toggle_cursor = "tab"
escape = "escape"
enter = "return"
move_forward = "w"
move_left = "a"
move_back = "s"
move_right = "d"
map = "m"
bag = "b"
quest_log = "l"
character_window = "c"
social = "o"
spellbook = "p"
settings = "n"
help = "f1"
interface = "f2"
