[workspace]

[package]
name = "fileshare"
version = "0.1.0"
authors = ["Marcel Märtens <marcel.cochem@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uvth = "3.1"
network = { package = "veloren_network", path = "../../../network" }
clap = "2.33"
async-std = { version = "1.5", default-features = false }
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.2.3"
bincode = "1.2"
serde = { version = "1.0", features = ["derive"] }
rand = "0.7.3"
shellexpand = "2.0.0"