check:
  extends: .recompile
  stage: check-compile
  tags:
    - veloren-docker
  script:
    - ln -s /dockercache/cache-all target
    - RUSTFLAGS="-D warnings" cargo check --locked

code-quality:
  extends: .recompile
  stage: check-compile
  tags:
    - veloren-docker
  script:
    - ln -s /dockercache/cache-all target
    - cargo clippy -- --warn clippy::all
    - cargo fmt --all -- --check

security:
  extends: .recompile
  stage: check-compile
  allow_failure: true
  tags:
    - veloren-docker
  script:
    - ln -s /dockercache/cache-all target
    - cargo audit
