# Template to only run if actual changes has been made to the code and not just documentation
.only: &only
  rules:
    - changes:
        - "*.{rs,ron,toml}"

check:
  <<: *only
  stage: check-compile
  tags:
    - veloren-docker
  script:
    - RUSTFLAGS="-D warnings" cargo check --locked

code-quality:
  <<: *only
  stage: check-compile
  tags:
    - veloren-docker
  script:
    - cargo clippy -- --warn clippy::all
    - cargo fmt --all -- --check

security:
  <<: *only
  stage: check-compile
  allow_failure: true
  tags:
    - veloren-docker
  script:
    - cargo audit
